[".vendor/font-powerline"]
  type = "archive"
  url = "https://github.com/powerline/fonts/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".vendor/font-jetbrains"]
  type = "archive"
  url = "https://github.com/JetBrains/JetBrainsMono/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".vendor/git-quick-stats"]
  type = "archive"
  url = "https://github.com/arzzen/git-quick-stats/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".vendor/git-extras"]
  type = "archive"
  url = "https://github.com/tj/git-extras/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".vendor/iterm"]
  type = "archive"
  url = "https://github.com/mbadolato/iTerm2-Color-Schemes/archive/master.tar.gz"
  exact = true
  stripComponents = 1
