#!/usr/bin/env bash

defaults write com.googlecode.iterm2 AppleAntiAliasingThreshold -int 1
defaults write com.googlecode.iterm2 ApplePressAndHoldEnabled -int 0
defaults write com.googlecode.iterm2 AppleScrollAnimationEnabled -int 0
defaults write com.googlecode.iterm2 AppleSmoothFixedFontsSizeThreshold -int 1
defaults write com.googlecode.iterm2 AppleWindowTabbingMode -string "manual"
defaults write com.googlecode.iterm2 DimBackgroundWindows -int 0
defaults write com.googlecode.iterm2 DimOnlyText -int 1
defaults write com.googlecode.iterm2 HapticFeedbackForEsc -int 1
defaults write com.googlecode.iterm2 HideFromDockAndAppSwitcher -int 1
defaults write com.googlecode.iterm2 HideMenuBarInFullscreen -int 0
defaults write com.googlecode.iterm2 HideScrollbar -int 1
defaults write com.googlecode.iterm2 HideTab -int 0
defaults write com.googlecode.iterm2 Hotkey -int 1
defaults write com.googlecode.iterm2 HotkeyChar -int 96
defaults write com.googlecode.iterm2 HotkeyCode -int 50
defaults write com.googlecode.iterm2 HotkeyMigratedFromSingleToMulti -int 1
defaults write com.googlecode.iterm2 HotkeyModifiers -int 1573160
defaults write com.googlecode.iterm2 PasteTabToStringTabStopSize -int 4
defaults write com.googlecode.iterm2 PreventEscapeSequenceFromClearingHistory -int 0
defaults write com.googlecode.iterm2 SUFeedURL -string "https://iterm2.com/appcasts/testing_modern.xml?shard=72"
defaults write com.googlecode.iterm2 SavePasteHistory -int 1
defaults write com.googlecode.iterm2 ShowBookmarkName -int 0
defaults write com.googlecode.iterm2 ShowFullScreenTabBar -int 0
defaults write com.googlecode.iterm2 SplitPaneDimmingAmount -float 0.6
defaults write com.googlecode.iterm2 StretchTabsToFillBar -int 0
defaults write com.googlecode.iterm2 TabStyleWithAutomaticOption -int 5
defaults write com.googlecode.iterm2 VisualIndicatorForEsc -int 0
