name: release

on:
  push:
    branches:
      - main

jobs:
  codespaces:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/universal:linux
      env:
        CODESPACES: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: /github/home/.dotfiles

      - name: Install dotfiles
        run: |
          ls -lahH
          pwd
          ls -lahH /github/home
          ./install.sh

      - name: Dump data
        run: |
          "$HOME/.local/bin/chezmoi" data

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate documentation
        run: |
          mkdir -p dist
          cp README.md dist/index.md
          cp -R screenshots/ dist/screenshots/
          cp _config.yml dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: true
